version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB: "postgres://postgres:password@db:5432"
  db:
    image: postgres
    volumes:
      - "db_volume:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskalla
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: taskalla@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "3001:80"
volumes:
  db_volume:
