# This file is intended for development, and not for use in production.

version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB: "postgres://postgres:password@db:5432/taskalla"
  db:
    image: postgres
    volumes:
      - "db_volume:/var/lib/postgresql/data"
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./sql/mock.sql:/docker-entrypoint-initdb.d/mock.sql"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskalla
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "3001:8081"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/taskalla?sslmode=disable
    depends_on:
      - db
volumes:
  db_volume:
