name: Format
on:
  - push
  - pull_request
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: test -z `gofmt -l ./..`
